### PR TITLE
Fix `to_bytes()` for `ProjectivePoint::identity()`

### LINKED ISSUE #442: `<ProjectivePoint as GroupEncoding>::to_bytes()` can panic
For example when you use `ProjectivePoint::identity()`, the size that `to_bytes()` will attempt to convert with `clone_from_slice` will only be 1, but it expects 33.

### PR DESCRIPTION
**Pull request by daxpedda**
This could maybe alternatively be fixed "upstream" in `EncodedPoint::len()`?
Fixes #442.

### CODE REVIEW

**Comment by tarcieri** [comment]
This is an unfortunate mismatch between the `GroupEncoding` API and SEC1 encoding.

> This could maybe alternatively be fixed "upstream" in EncodedPoint::len()?

`EncodedPoint::len` is doing the right thing: the SEC1 encoding for the identity point is a 1-byte `0` tag.

Technically this is an invalid SEC1 encoding, but there's nothing else that can be done with a fixed-sized `GroupEncoding::Repr`, and it's certainly preferable to panicking.

File: p256/src/arithmetic/projective.rs [hunk 1]
```diff
@@ -665,4 +669,9 @@ mod tests {
             assert_eq!(res.y.to_bytes(), coords.1.into());
         }
     }
+
+    #[test]
+    fn projective_to_bytes() {
+        assert_eq!([0; 33], ProjectivePoint::identity().to_bytes().as_slice());
+    }
```
Comment (tarcieri) [inline p256/src/arithmetic/projective.rs:676]: It would be good to make a note that this test is specifically for the identity point, and that the result is technically/deliberately an invalid SEC1 encoding.

**Comment by daxpedda** [comment]
> Technically this is an invalid SEC1 encoding, but there's nothing else that can be done with a fixed-sized `GroupEncoding::Repr`, and it's certainly preferable to panicking.

We could change the interface to return an `Option`?

**Comment by tarcieri** [comment]
`GroupEncoding` is defined in the `group` crate, so the change would have to be made there.

Really it's an eccentricity of the SEC1 encoding, and I doubt they would want to make the API fallible just to support that.

**Comment by daxpedda** [comment]
> `GroupEncoding` is defined in the `group` crate, so the change would have to be made there.

Ah, I wasn't aware this isn't owned by RustCrypto.

File: p256/src/arithmetic/projective.rs (hunk 1 above)
Comment (daxpedda) [reply p256/src/arithmetic/projective.rs]: I hope this is enough:
https://github.com/RustCrypto/elliptic-curves/blob/0ba5440254df0928c69b80cf6e74182931182141/p256/src/arithmetic/projective.rs#L674-L675

**Comment by tarcieri** [comment]
It'd also be good to make sure that `GroupEncoding::from_bytes` can decode this encoding, and also that the problem is also solved for the `GroupEncoding` impl on `AffinePoint`.

**Comment by tarcieri** [comment]
This is fine as a start. I'll take care of the other comments I raised.
