### PR TITLE
ed448-goldilocks: rename `FieldElement::sqrt()` to `unchecked_sqrt()`

### LINKED ISSUE #1509: ed448-goldilocks: `FieldElement::sqrt` should verify candidate square root is a valid quadratic residue
Currently `FieldElement::sqrt` is infallible and does not ensure a candidate square root it computes is actually a valid quadratic residue.

This means it may return incorrect results in the event the input isn't actually a perfect square to begin with.

The code was adapted from `crrl`, which validates candidate square roots by squaring them and ensuring the result is equal to the input: https://github.com/pornin/crrl/blob/4cc7cbbe8796ee8d459b815d81318603279879e4/src/backend/w64/gf448.rs#L1639-L1646

`Scalar::sqrt` handles this correctly

cc @daxpedda

### PR DESCRIPTION
**Pull request by daxpedda**
Fixes #1509.

### CODE REVIEW

File: ed448-goldilocks/src/field/element.rs [hunk 1]
```diff
@@ -337,7 +337,7 @@ impl FieldElement {
         !Choice::from(self.0.jacobi_symbol().is_minus_one())
     }
 
-    pub fn sqrt(&self) -> FieldElement {
+    pub fn unchecked_sqrt(&self) -> FieldElement {
```
Comment (tarcieri) [inline ed448-goldilocks/src/field/element.rs:340]: I'd say "perhaps this shouldn't be pub" but I guess we don't expose `FieldElement` anywhere yet.

Sidebar: perhaps we should enable the `unreachable_pub` lint...
