### PR TITLE
sm2: bring signature and key encoding support

### LINKED ISSUE #1126: feat: support sm2::dsa::SigningKey for x509_cert::builder::RequestBuilder::new
version:

```toml
sm2 = "0.13.3"
```

example:

```rust
pub fn generate_sm2_csr(pri_key: SecretKey, name: Name) {
    let signer = sm2::dsa::SigningKey::new("", &pri_key).unwrap();
    let csr = RequestBuilder::new(name, &signer)
      .and_then(|b| b.build()).unwrap();
  }
```

error message:

```txt
error[E0277]: the trait bound `sm2::dsa::VerifyingKey: EncodePublicKey` is not satisfied
   --> src/csr.rs:32:41
    |
32  |     let csr = RequestBuilder::new(name, &signer)
    |               -------------------       ^^^^^^^ the trait `EncodePublicKey` is not implemented for `sm2::dsa::VerifyingKey`
    |               |
    |               required by a bound introduced by this call
    |
    = help: the following other types implement trait `EncodePublicKey`:
              rsa::RsaPublicKey
              rsa::pkcs1v15::VerifyingKey<D>
              rsa::pss::VerifyingKey<D>
              sm2::elliptic_curve::PublicKey<C>
note: required by a bound in `RequestBuilder::<'s, S>::new`
```

it seems some impl is missing, like `impl SignatureBitStringEncoding for Signature`, `impl SignatureAlgorithmIdentifier for VerifyingKey`, and so on. Crypto code is challenging to me, and I fail to reair it myself.

[GMObjectIdentifiers](https://github.com/bcgit/bc-java/blob/main/core/src/main/java/org/bouncycastle/asn1/gm/GMObjectIdentifiers.java) .

### PR DESCRIPTION
**Pull request by baloo**
Fixes #1126

### CODE REVIEW

**Comment by baloo** [comment]
cc @dlzht

**Review by dlzht — APPROVED** [review]
it works for me

**Comment by dlzht** [comment]
I use `CertificateBuilder::new` to generate sm2 certificate, and there are some differences between this certificate and the one I generated using other tools.



how can i change signature algorithm to SM3? @baloo

File: sm2/src/dsa.rs [hunk 1]
```diff
@@ -197,3 +204,20 @@ impl TryFrom<&[u8]> for Signature {
...
+        der::asn1::BitString::new(0, self.to_vec())
+    }
+}
+
+#[cfg(all(feature = "alloc", feature = "pkcs8"))]
+impl AssociatedAlgorithmIdentifier for Signature {
+    type Params = AnyRef<'static>;
+
+    const ALGORITHM_IDENTIFIER: AlgorithmIdentifierRef<'static> = AlgorithmIdentifierRef {
+        oid: <Sm2 as AssociatedOid>::OID,
```
Comment (tarcieri) [inline sm2/src/dsa.rs:220]: Looks like this needs to be a slightly different OID (ending in 501 instead of 301)

**Comment by baloo** [comment]
Made a prototype with this branch: https://github.com/baloo/sm2-cert

```
$ cargo run | openssl req -in foo.csr -text
Certificate Request:
    Data:
        Version: 1 (0x0)
        Subject: CN = foo.example
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub:
                    04:fe:e2:c5:7d:7e:e0:6a:f2:c1:53:1e:d7:c8:4b:
                    83:5d:64:c5:8c:90:54:2f:89:5e:b6:b8:93:12:e1:
                    d3:10:12:d5:ad:ae:dc:51:6c:87:57:d5:a6:81:a4:
                    e4:23:d4:8f:dd:30:03:0a:30:7e:14:e8:d2:a5:cb:
                    cd:87:6a:97:a5
                ASN1 OID: SM2
        Attributes:
            Requested Extensions:
    Signature Algorithm: SM2-with-SM3
    Signature Value:
        03:52:bd:39:37:15:b2:50:1b:60:db:35:d7:e4:5f:07:ac:ef:
        9a:66:ce:69:18:31:b2:f5:d4:69:93:46:78:b7:e9:3c:47:90:
        bf:09:34:a3:3f:fb:5b:32:e0:28:f0:22:a1:c1:80:08:6d:6f:
        80:eb:2b:83:3f:ae:5a:be:cd:78
-----BEGIN CERTIFICATE REQUEST-----
MIHbMIGJAgEAMBYxFDASBgNVBAMMC2Zvby5leGFtcGxlMFkwEwYHKoZIzj0CAQYI
KoEcz1UBgi0DQgAE/uLFfX7gavLBUx7XyEuDXWTFjJBUL4letriTEuHTEBLVra7c
UWyHV9WmgaTkI9SP3TADCjB+FOjSpcvNh2qXpaARMA8GCSqGSIb3DQEJDjECMAAw
CgYIKoEcz1UBg3UDQQADUr05NxWyUBtg2zXX5F8HrO+aZs5pGDGy9dRpk0Z4t+k8
R5C/CTSjP/tbMuAo8CKhwYAIbW+A6yuDP65avs14
-----END CERTIFICATE REQUEST-----
```

**Comment by baloo** [comment]
@tarcieri can I get a merge on this one?

**Review by tarcieri — APPROVED** [review]
